name: Test workflow for Python template
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Create virtual env
      run: |
        make env
    - name: Install dependencies
      run: |
        make install
    - name: Create the dataset
      run: |
        make create_table
    - name: test connection
      run: |
        make test
      
    - name: Lint with pylint
      run: |
        make lint
    - name: Format code
      run: |
        make format

  

    
    

    
    
